server:
  port: 8081
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/project_security
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 402654233491-7ijmuu4r7ri4bdobm0eebt8i71fqlp51.apps.googleusercontent.com
            clientSecret: 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
            scope:
              - email
              - profile
